DROP TABLE IF EXISTS BARCODE;

CREATE TABLE BARCODE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  barcode NVARCHAR(25) NOT NULL/*,
  unique(barcode)*/
);

ALTER TABLE BARCODE ADD CONSTRAINT CK_barcode_min_legth13 CHECK (LENGTH(barcode) >= 13);
ALTER TABLE BARCODE ADD CONSTRAINT CK_barcode_no_space CHECK (POSITION(' ',barcode ) < 1);
ALTER TABLE BARCODE ADD CONSTRAINT CK_barcode_only_uper CHECK (UPPER(barcode) = barcode);
ALTER TABLE BARCODE ADD CONSTRAINT UQ_barcode unique(barcode);